import { StyleSheet } from 'react-native';
import { C, radius } from '../../theme';

export const fs = StyleSheet.create({
  heroValue: { fontSize: 42, fontWeight: '900', color: C.white, letterSpacing: -1 },
  heroUnit: { fontSize: 14, color: '#91c5ff' },
  coreLiftRow: { flexDirection: 'row', gap: 7, marginBottom: 14 },
  coreLift: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderRadius: radius.md,
    backgroundColor: C.panel,
    borderWidth: 1,
    borderColor: C.line,
  },
  coreLiftActive: { backgroundColor: C.blueDim, borderColor: C.blue },
  coreLiftText: { fontSize: 11, fontWeight: '800', textAlign: 'center', color: C.muted },
  searchResults: {
    backgroundColor: C.panel,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    marginTop: -8,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: C.line,
  },
  searchResult: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
  },
  progressHeading: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10 },
  chartCaption: { fontSize: 11, fontWeight: '700', color: C.muted, marginBottom: 8 },
  statSection: {
    backgroundColor: C.panel,
    borderRadius: radius.lg,
    padding: 15,
    marginTop: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  statTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  bestSetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  bestSetCard: {
    width: '31%',
    minHeight: 82,
    padding: 10,
    borderRadius: radius.md,
    backgroundColor: C.raised,
  },
  bestSetValue: { fontSize: 17, fontWeight: '900', color: C.text, marginTop: 7 },
  chartSelection: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '800',
    color: C.blue,
    marginBottom: 8,
  },
  improvementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  improvementPercent: { fontSize: 22, fontWeight: '900' },
  miniSegments: { flexDirection: 'row', gap: 6, marginVertical: 12 },
  miniSegment: {
    flex: 1,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: C.raised,
  },
  miniSegmentActive: { backgroundColor: C.blue },
  miniSegmentText: { fontSize: 11, fontWeight: '800', color: C.muted },
  ringLayout: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  ringLegend: { flex: 1, paddingVertical: 5 },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 24 },
  legendValue: { fontSize: 11, fontWeight: '800', color: C.text },
  heatLegend: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 5,
    marginTop: 8,
  },
  heatCell: { width: 12, height: 12, borderRadius: 3 },
  lineChart: {
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: C.panel,
    borderRadius: radius.lg,
    paddingTop: 4,
    marginBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  graphTooltip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 13,
    borderRadius: radius.md,
    backgroundColor: C.blueDim,
    marginBottom: 12,
  },
  tooltipValue: { fontSize: 22, fontWeight: '900', color: C.white, marginTop: 2 },
  tooltipSet: { fontSize: 13, fontWeight: '800', color: '#91c5ff' },
  record: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
});
