import { StyleSheet } from 'react-native';
import { C, radius } from './theme';

export const s = StyleSheet.create({
  flex: { flex: 1 },
  screen: { flex: 1, backgroundColor: C.bg },
  center: { alignItems: 'center', justifyContent: 'center' },
  content: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 36 },
  loading: { fontWeight: '900', letterSpacing: 3, color: C.blue },
  tabs: {
    height: 66,
    flexDirection: 'row',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
    backgroundColor: C.panel,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 },
  tabLabel: { fontSize: 10, fontWeight: '600', color: C.muted },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  brand: { fontSize: 10, fontWeight: '900', letterSpacing: 2.2, color: C.blue },
  title: { fontSize: 30, fontWeight: '800', color: C.text, letterSpacing: -0.8 },
  link: { fontSize: 16, fontWeight: '700', color: C.blue },
  dateStrip: { padding: 18, borderRadius: radius.lg, backgroundColor: C.blueDim, marginBottom: 12 },
  overline: { fontSize: 11, fontWeight: '800', letterSpacing: 1.4, color: C.muted },
  bigDate: { fontSize: 30, fontWeight: '800', color: C.white, marginTop: 5 },
  dateInput: { color: '#91c5ff', fontSize: 12, marginTop: 4, padding: 0 },
  empty: { alignItems: 'center', paddingVertical: 46, paddingHorizontal: 28 },
  emptyTitle: { fontSize: 20, fontWeight: '800', color: C.text, marginTop: 14 },
  emptyCopy: { fontSize: 14, lineHeight: 20, textAlign: 'center', color: C.muted, marginTop: 6 },
  button: {
    minHeight: 48,
    borderRadius: radius.md,
    backgroundColor: C.blue,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    marginVertical: 6,
  },
  buttonGhost: { backgroundColor: 'transparent', borderWidth: 1, borderColor: C.blue },
  buttonDanger: { backgroundColor: C.red },
  buttonText: { fontSize: 15, fontWeight: '800', color: C.white },
  card: {
    backgroundColor: C.panel,
    borderRadius: radius.lg,
    padding: 15,
    marginBottom: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  cardHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  dragHandle: { width: 30, minHeight: 36, alignItems: 'center', justifyContent: 'center' },
  cardTitle: { fontSize: 17, fontWeight: '800', color: C.text },
  rowSub: { fontSize: 12, color: C.muted, marginTop: 3, lineHeight: 17 },
  setRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginVertical: 4 },
  setNo: { width: 32, textAlign: 'center', fontSize: 13, fontWeight: '800', color: C.muted },
  setInput: {
    flex: 1,
    minWidth: 0,
    height: 40,
    borderRadius: 8,
    backgroundColor: C.raised,
    color: C.text,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
  },
  addSet: {
    height: 42,
    marginTop: 9,
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: C.raised,
  },
  addSetText: { color: C.blue, fontSize: 12, fontWeight: '900', letterSpacing: 0.8 },
  modalHead: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomColor: C.line,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  modalTitle: { fontSize: 16, fontWeight: '800', color: C.text },
  search: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: C.raised,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  searchInput: { flex: 1, color: C.text, fontSize: 16 },
  filterRow: { gap: 7, paddingBottom: 14 },
  filterChip: {
    height: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    borderRadius: 17,
    backgroundColor: C.panel,
    borderWidth: 1,
    borderColor: C.line,
  },
  filterChipActive: { backgroundColor: C.blueDim, borderColor: C.blue },
  filterChipText: { fontSize: 12, fontWeight: '700', color: C.muted },
  filterChipTextActive: { color: C.white },
  categorySwatch: { width: 10, height: 10, borderRadius: 5 },
  label: { fontSize: 11, fontWeight: '800', letterSpacing: 1.2, color: C.muted, marginBottom: 7 },
  helper: { fontSize: 12, color: C.muted, lineHeight: 18, marginBottom: 8 },
  input: {
    height: 44,
    borderRadius: radius.sm,
    backgroundColor: C.raised,
    paddingHorizontal: 12,
    color: C.text,
    fontSize: 16,
    marginBottom: 8,
  },
  unitLabel: { fontSize: 9, fontWeight: '800', color: C.muted },
  row: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
  },
  exerciseIcon: {
    height: 36,
    width: 36,
    borderRadius: 10,
    backgroundColor: C.blueDim,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowTitle: { fontSize: 15, fontWeight: '700', color: C.text },
  calendar: {
    backgroundColor: C.panel,
    borderRadius: radius.lg,
    padding: 12,
    marginBottom: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  calendarNav: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  calendarArrow: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  calendarTitle: { fontSize: 17, fontWeight: '800', color: C.text },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  weekday: {
    width: '14.285%',
    textAlign: 'center',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
    color: C.muted,
    paddingVertical: 8,
  },
  calendarCell: {
    width: '14.285%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  daySelected: { backgroundColor: C.blue },
  dayText: { fontSize: 14, fontWeight: '700', color: C.text },
  dayTextSelected: { color: C.white, fontWeight: '900' },
  workoutDots: {
    position: 'absolute',
    bottom: 3,
    flexDirection: 'row',
    gap: 2,
    maxWidth: 30,
    justifyContent: 'center',
  },
  workoutDot: { width: 4, height: 4, borderRadius: 2 },
  selectedDate: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
    color: C.muted,
    marginBottom: 9,
    marginLeft: 4,
  },
  segmented: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: radius.md,
    backgroundColor: C.panel,
    marginVertical: 10,
  },
  segment: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  segmentActive: { backgroundColor: C.blue },
  segmentText: { fontSize: 12, fontWeight: '800', color: C.muted },
  segmentTextActive: { color: C.white },
});
